In [3]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [4]:
documents = [
    "people watch movie",
    "people watch cricket",
    "people like movie",
    "people like cricket",
]

In [5]:
tokens = [sentences.lower().split() for sentences in documents]

In [6]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [9]:
all_words = [[word] for sentences in tokens for word in sentences]

In [10]:
all_words

[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['people'],
 ['like'],
 ['cricket']]

In [11]:
encoder = OneHotEncoder(sparse_output=False).fit(all_words)

In [ ]:
encoder.categories_

[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]


In [16]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']


In [17]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [23]:
for sentences in tokens:
        encoded_sentence = encoder.transform([[word] for word in sentences])
        print("\nsentence:", sentences)
        print("encoded:\n", encoded_sentence) 


sentence: ['people', 'watch', 'movie']
encoded:
 [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

sentence: ['people', 'watch', 'cricket']
encoded:
 [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

sentence: ['people', 'like', 'movie']
encoded:
 [[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

sentence: ['people', 'like', 'cricket']
encoded:
 [[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
