In [21]:
from gensim.models import Word2Vec, keyedvectors
import gensim.downloader as api


In [22]:
model = api.load("word2vec-google-news-300")

In [23]:
model['sunny']

array([ 1.59179688e-01,  1.07910156e-01,  3.71093750e-02,  1.61132812e-01,
        3.02734375e-01, -3.35937500e-01, -3.83300781e-02, -1.32751465e-03,
       -8.69140625e-02,  2.25585938e-01,  2.23388672e-02,  1.35742188e-01,
       -1.04003906e-01,  1.73828125e-01,  5.46875000e-02,  1.13769531e-01,
       -1.53320312e-01,  2.29492188e-01,  1.13769531e-01,  1.61132812e-02,
       -1.46484375e-01,  5.07812500e-01, -1.08886719e-01, -1.59179688e-01,
       -9.37500000e-02, -6.64062500e-02,  1.90429688e-01,  2.49023438e-01,
       -1.08398438e-01,  2.00195312e-01, -2.19726562e-01,  8.83789062e-02,
        4.98046875e-02,  4.27246094e-02, -3.02734375e-01, -1.64062500e-01,
       -9.86328125e-02, -2.61718750e-01,  1.49414062e-01,  2.12890625e-01,
        2.38281250e-01, -1.50390625e-01,  1.82617188e-01,  1.18408203e-02,
        1.85546875e-02, -1.41601562e-01, -1.41601562e-01,  3.14941406e-02,
       -2.50000000e-01,  2.55859375e-01,  2.53906250e-01,  3.69140625e-01,
        4.43359375e-01,  

In [24]:
len(model['sunny'])

300

In [25]:
model['Bajpayee']

array([ 7.76367188e-02, -1.53198242e-02,  3.14453125e-01, -7.12890625e-02,
       -1.03027344e-01, -2.14843750e-01,  2.88391113e-03, -1.50390625e-01,
       -1.24511719e-01, -1.74560547e-02,  1.66015625e-01, -5.32226562e-02,
       -5.34667969e-02, -9.17968750e-02, -1.49414062e-01,  2.65625000e-01,
        2.08984375e-01, -1.39648438e-01, -1.06933594e-01,  1.26953125e-01,
        2.58789062e-02,  6.40869141e-03,  7.42187500e-02,  2.28271484e-02,
        7.27539062e-02, -2.28515625e-01, -2.75390625e-01, -1.69921875e-01,
        6.19506836e-03, -1.69921875e-01, -3.32031250e-01, -2.08984375e-01,
       -9.17968750e-02, -4.11987305e-03,  1.83105469e-02, -9.47265625e-02,
       -1.03515625e-01,  5.95703125e-02,  3.02734375e-01, -2.06054688e-01,
        1.81640625e-01,  8.20312500e-02, -7.66601562e-02,  2.85156250e-01,
       -1.25000000e-01, -3.10546875e-01, -1.37695312e-01, -2.29492188e-02,
        1.74804688e-01, -7.56835938e-02,  2.13623047e-03, -9.57031250e-02,
        1.28906250e-01,  

In [26]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [27]:
model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [28]:
model.similarity('man', 'woman')

np.float32(0.76640123)

In [29]:
model.similarity('happy', 'joyful')

np.float32(0.42381963)

In [30]:
model.similarity('mutton', 'chicken')    

np.float32(0.56266904)

In [31]:
model.similarity('beer', 'whiskey')    

np.float32(0.63661695)

In [32]:
model.doesnt_match(["PHP","Python","Java","C++","DOG"])

'DOG'

In [33]:
vec = model['king'] - model['men'] + model['women']

In [34]:
model.most_similar([vec])

[('king', 0.8527070879936218),
 ('queen', 0.6743921637535095),
 ('monarch', 0.6191632151603699),
 ('kings', 0.5753854513168335),
 ('crown_prince', 0.562209963798523),
 ('princess', 0.543317437171936),
 ('prince', 0.5246985554695129),
 ('sultan', 0.5236638784408569),
 ('ruler', 0.5165805220603943),
 ('monarchy', 0.5113592147827148)]

In [42]:
sentence = "I love machine Learning"


In [43]:
words = sentence.lower().split()

In [44]:
word_vectors = []

In [45]:
for word in words:
    print(word)
    word_vectors.append(model[word])

i
love
machine
learning


In [41]:
word_vectors

[array([-2.25585938e-01, -1.95312500e-02,  9.08203125e-02,  2.37304688e-01,
        -2.92968750e-02,  9.32617188e-02, -5.88378906e-02, -4.10156250e-02,
         5.22460938e-02,  2.00195312e-02, -3.44238281e-02, -2.91015625e-01,
        -2.61718750e-01, -1.90429688e-01,  3.85742188e-02,  8.30078125e-03,
         3.14941406e-02,  7.47070312e-02,  1.14746094e-01,  1.24511719e-02,
        -2.11914062e-01,  1.28906250e-01,  2.55859375e-01,  1.08886719e-01,
        -7.03125000e-02,  1.60156250e-01, -4.00390625e-01, -1.16699219e-01,
        -3.22265625e-02, -6.73828125e-02,  1.55273438e-01,  1.25000000e-01,
        -6.22558594e-02,  3.56445312e-02, -1.79687500e-01,  1.58203125e-01,
        -2.53906250e-01,  1.74804688e-01, -1.18164062e-01, -2.19726562e-03,
         1.49536133e-02, -5.71289062e-02,  2.39257812e-01,  1.36718750e-01,
         1.47460938e-01,  7.08007812e-02,  1.72851562e-01, -2.38281250e-01,
        -5.71289062e-02, -1.04492188e-01,  2.23388672e-02,  8.74023438e-02,
         1.4